package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

public class VistaController {
	@FXML
	private TextField tctInicio;
	@FXML
	private TextField txtFin;
	@FXML
	private TextArea txtCamino;
	@FXML
	private Button btnEvaluar;
	@FXML
	private Button btnSalir;

	// Event Listener on Button[#btnEvaluar].onAction
	@FXML
	public void evaluar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSalir].onAction
	@FXML
	public void salir(ActionEvent event) {
		System.exit(0);
	}
}
